######################################################################
# Automatically generated by qmake (3.0) ven. juin 8 09:39:51 2018
######################################################################

TEMPLATE = app
TARGET = c++
INCLUDEPATH += .
LIBS += -lmysqlcppconn
CONFIG += c++11

# Input
HEADERS += Controls.hpp DataBase.hpp includes.hpp MainWindow.hpp
SOURCES += controls.cpp dataBase.cpp main.cpp mainWindow.cpp
QT += widgets
QT += core
QT += gui