######################################################################
# Automatically generated by qmake (3.0) jeu. juin 7 15:54:57 2018
######################################################################

TEMPLATE = app
TARGET = c++
INCLUDEPATH += .

# Input
HEADERS += Controls.hpp dataBase.hpp includes.hpp MainWindow.hpp
SOURCES += controls.cpp main.cpp mainWindow.cpp
QT += widgets
QT += core
QT += gui