######################################################################
# Automatically generated by qmake (3.0) lun. juin 4 15:26:03 2018
######################################################################

TEMPLATE = app
TARGET = c++
INCLUDEPATH += .

# Input
HEADERS += Controls.h dataBase.h MainWindow.h
SOURCES += controls.cpp main.cpp mainWindow.cpp
QT += widgets
QT += core
QT += gui